---
title: "Amygdala activity is higher on Motivation Consistent Trials"
output: html_document
---

```{r set-up, warning=FALSE, message=FALSE, results="hide"}
# Clear workspace
rm(list = ls())

library("tidyr")
library("dplyr")
library("ggplot2")
library("lmerTest")
library("Rarity")

design = "MotConInCon_cue_6dof_extendedmotion"
```

```{r}
## Load in z-stats
featquery_res = read.csv(file.path('../../3_results/2_glm/',design,'featquery_pe/roi_zstat.csv'))
featquery_res$Sub = as.factor(featquery_res$Sub)

## Load in behavioral bias
SubBias = read.csv('../../3_results/1_psychometric/SubBias.csv')
SubBias$Sub = factor(SubBias$Sub)
```

```{r fig.width = 3.6, fig.height=5.9}
full.model.subj_parm = left_join(featquery_res,SubBias)

full.model.subj_parm_long = gather(full.model.subj_parm,'parm','value',2:ncol(full.model.subj_parm)) %>%
  dplyr::filter(parm %in% c('amygdala_harvard_bin50'))

ggplot() +
  stat_summary(data = full.model.subj_parm_long, aes(x=parm,y=value),
               fun.y=mean,geom="bar",width=0.2,fill=NA,colour="#800000", lwd=1.2) +
  stat_summary(data = full.model.subj_parm_long, aes(x=parm,y=value),
               fun.data = mean_cl_normal, geom = "errorbar",width=0.1,
               fun.args = list(mult = 1), alpha = 0.6,colour="#800000",lwd=1.2) + 
  theme(legend.position="none",
      panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.x  = element_text(size=24,color="black"),
        axis.text.y  = element_text(size=20,color="black"),
        axis.title.x = element_text(size=24),
        axis.title.y = element_text(size=24),
        strip.background = element_blank(),
        strip.text.x = element_text(face = "bold", size = 25)) + xlab("") + ylab("z-statistic") + scale_x_discrete(labels=c("amygdala")) +  geom_point(data=full.model.subj_parm_long, aes(x=parm,y=value),size=.5)

t.test(full.model.subj_parm$amygdala_harvard_bin50, alternative=c("greater"))
```