---
title: "Amygdala DDM at time of cue"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, warning=FALSE, message=FALSE}
# Clear workspace
rm(list = ls())
# Load packages
library(tidyr)
library(plyr)
library(dplyr)

library(ggplot2)
library(lmerTest)

library(Hmisc)
library(car)

library(Rarity)
library(cowplot)
asNumeric <- function(x) as.numeric(as.character(x))
factorsNumeric <- function(d) modifyList(d, lapply(d[, sapply(d, is.factor)],   
                                                   asNumeric))
sem <- 
  function(x) {sd(x,na.rm = T) / sqrt(length(x))}
```

```{r}

d0 = read.csv("../../3_results/3_ddm/model_outputs/trace/cue_full_model_trace.csv", header = F) 

colnames(d0) = c("a", "t", "z_intercept", "z_condition_amygdala_pe", "z_amygdala_pe", "z_condition", "v_intercept", "v_condition_amygdala_pe", "v_amygdala_pe", "v_condition", "v_stim")
```

### v_condition_amygdala_pe

```{r}
# v_condition_amygdala_pe
v_condition_amygdala_pe_95 = quantile(d0$v_condition_amygdala_pe,0.05)
v_condition_amygdala_pe = d0$v_condition_amygdala_pe
v_condition_amygdala_pe = as.data.frame(v_condition_amygdala_pe)

# Credible intervals
quantile(d0$v_condition_amygdala_pe,c(0.025,0.975))
mean(d0$v_condition_amygdala_pe)
mean(d0$v_condition_amygdala_pe > 0)
plot.v_condition_amygdala_pe = 
  ggplot(v_condition_amygdala_pe,aes(v_condition_amygdala_pe, y = ..scaled..)) +
  geom_density(alpha = 0.2, adjust = 5, size = 0) +
  geom_line(stat = "density", adjust = 5, size = 1) +
  geom_vline(xintercept = 0, size = 0.5, linetype="dashed") + 
  theme(legend.position = "none",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.x  = element_text(size=10,color="black"),
        axis.text.y  = element_text(size=10,color="black"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=10),
        strip.background = element_blank(),
        strip.text.x = element_text(face = "bold", size = 10),
        plot.title = element_text(hjust = 0.5,face = "bold", size = (12))) +
  ylab("Density") +
  coord_cartesian(ylim=c(0, 1.1), xlim = c(-0.15, 0.201)) +
  scale_y_continuous(breaks=seq(0,1,0.25)) +
  scale_x_continuous(breaks=seq(from = -0.1, to = 0.2, by = 0.1)) +
  ggtitle("p(v_cond_amyg)")

# Shade area
plot_data <- as.data.frame(ggplot_build(plot.v_condition_amygdala_pe)$data[2])
plot.v_condition_amygdala_pe = plot.v_condition_amygdala_pe + 
  geom_area(data = subset(plot_data, x > 0.0001), aes(x=x, y=y-0.0002), fill="grey", alpha = 0.8) + 
  geom_line(stat = "density", adjust = 5, size = 1)
```

### z_condition_amygdala_pe
```{r}
# z_condition_amygdala_pe
z_condition_amygdala_pe_95 = quantile(d0$z_condition_amygdala_pe,0.05)
z_condition_amygdala_pe = d0$z_condition_amygdala_pe
z_condition_amygdala_pe= as.data.frame(z_condition_amygdala_pe)

# Credible intervals
quantile(d0$z_condition_amygdala_pe,c(0.025,0.975))
mean(d0$z_condition_amygdala_pe)
mean(d0$z_condition_amygdala_pe > 0)

plot.z_condition_amygdala_pe = 
  ggplot(z_condition_amygdala_pe,aes(z_condition_amygdala_pe, y = ..scaled..)) +
  geom_density(alpha = 0.2, adjust = 5, size = 0) +
  geom_line(stat = "density", adjust = 5, size = 1) +
  geom_vline(xintercept = 0, size = 0.5, linetype="dashed") + 
  theme(legend.position = "none",
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"),
        axis.text.x  = element_text(size=10,color="black"),
        axis.text.y  = element_text(size=10,color="black"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=10),
        strip.background = element_blank(),
        strip.text.x = element_text(face = "bold", size = 10),
        plot.title = element_text(hjust = 0.5,face = "bold", size = (12))) +
  ylab("Density") +
  coord_cartesian(ylim=c(0, 1.1), xlim = c(-0.05, 0.05)) +
  scale_y_continuous(breaks=seq(0,1,0.25)) +
  scale_x_continuous(breaks=seq(from = -0.05, to = 0.05, by = 0.05)) +
  ggtitle('p(z_cond_amyg)')

# Shade area
plot_data <- as.data.frame(ggplot_build(plot.z_condition_amygdala_pe)$data[2])
plot.z_condition_amygdala_pe = plot.z_condition_amygdala_pe + 
  geom_area(data = subset(plot_data, x > 0.0001), aes(x=x, y=y-0.0002), fill="grey", alpha = 0.8) + 
  geom_line(stat = "density", adjust = 5, size = 1)
```


```{r fig.width = 6, fig.height = 2.5}
thisplot = plot_grid(plot.z_condition_amygdala_pe, plot.v_condition_amygdala_pe,nrow = 1)
thisplot
```

```{r}
cat("P(v_cond_amyg > 0) =", round(mean(d0$v_condition_amygdala_pe > 0),3),
    ", mean =", round(mean(d0$v_condition_amygdala_pe),3),
    "95% CI =", round(quantile(d0$v_condition_amygdala_pe,c(0.025,0.975)),3))
cat("P(z_cond_amyg > 0) =", round(mean(d0$z_condition_amygdala_pe > 0),3),
    ", mean =", round(mean(d0$z_condition_amygdala_pe),3),
    "95% CI =", round(quantile(d0$z_condition_amygdala_pe,c(0.025,0.975)),3))
```